name: cv3
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=11.8
  - numpy
  - pyyaml
  - opencv
  - scikit-image
  - matplotlib
  - pillow
  - tqdm
  - pip:
      - -r requirements_part3.txt
