name: cv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pyyaml
  - tqdm
  - pillow
  - pip:
      - opencv-python>=4.8.0
      - ultralytics>=8.1.0
      - scikit-image>=0.21.0
      - torch>=2.1.0
      - torchvision>=0.16.0
